# Generated by Django 4.2 on 2023-06-01 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diveshopmanagement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="name",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 6, 1, 14, 10, 7, 338625, tzinfo=datetime.timezone.utc
                ),
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
