# Generated by Django 4.2.1 on 2023-05-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diveshopmanagement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
            },
        ),
        migrations.RemoveField(
            model_name="customer",
            name="certification",
        ),
        migrations.AddField(
            model_name="customer",
            name="certifications",
            field=models.ManyToManyField(
                blank=True,
                related_name="customers",
                to="diveshopmanagement.certification",
                verbose_name="certifications",
            ),
        ),
    ]
