# Generated by Django 4.2 on 2023-05-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diveshopmanagement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airfill",
            name="oxygen_percentage",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
