# Generated by Django 4.2.1 on 2023-05-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "diveshopmanagement",
            "0002_certification_remove_customer_certification_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="notes",
        ),
        migrations.AlterField(
            model_name="customer",
            name="medical_conditions",
            field=models.TextField(default="NKDA"),
        ),
    ]
