# Generated by Django 4.2 on 2023-06-02 03:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diveshopmanagement", "0003_compressor_remove_customer_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="compressor",
            old_name="start_time",
            new_name="date_turned_on",
        ),
    ]
