# Generated by Django 4.2.1 on 2023-05-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diveshopmanagement", "0004_customer_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopifyuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
