# Generated by Django 4.2.1 on 2023-05-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diveshopmanagement", "0005_alter_shopifyuser_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
    ]
