# Generated by Django 4.2 on 2023-05-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Compressor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("hours", models.IntegerField()),
                ("last_filter_change", models.DateField()),
                ("last_oil_change", models.DateField()),
            ],
        ),
    ]
