# Generated by Django 4.2 on 2023-04-29 02:27

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="add_diver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="First and Last Name", max_length=100),
                ),
                ("certification_number", models.IntegerField()),
                (
                    "certification_agency",
                    models.CharField(
                        choices=[
                            ("PADI", "PADI"),
                            ("NAUI", "NAUI"),
                            ("SSI", "SSI"),
                            ("BSAC", "BSAC"),
                            ("CMAS", "CMAS"),
                            ("SDI", "SDI"),
                            ("TDI", "TDI"),
                            ("IANTD", "IANTD"),
                            ("SDI", "SDI"),
                        ],
                        max_length=100,
                    ),
                ),
                ("Date_of_birth", models.DateField()),
                (
                    "student_insurance",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        help_text="Yes or No",
                        max_length=5,
                    ),
                ),
                (
                    "dan_insurance",
                    models.CharField(
                        blank=True,
                        help_text="Type in Dan Insurance Number",
                        max_length=100,
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                (
                    "phone_number",
                    phone_field.models.PhoneField(
                        blank=True, help_text="Contact phone number", max_length=31
                    ),
                ),
                (
                    "address",
                    models.CharField(help_text="Street Address", max_length=100),
                ),
                ("city", models.CharField(help_text="City", max_length=100)),
                ("state", models.CharField(help_text="State", max_length=100)),
                ("zip", models.IntegerField(help_text="Zip Code")),
                (
                    "shirt_size",
                    models.CharField(
                        choices=[
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                            ("XXL", "Extra Extra Large"),
                            ("XXXL", "Extra Extra Extra Large"),
                        ],
                        max_length=4,
                    ),
                ),
            ],
        ),
    ]
