# Generated by Django 4.2 on 2023-04-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("add_diver", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="add_diver",
            name="student_insurance",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                help_text="Yes or No",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="add_diver",
            name="zip",
            field=models.IntegerField(help_text="Zip Code"),
        ),
    ]
