# Generated by Django 4.2 on 2023-05-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("add_diver", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="add_diver",
            name="dan_insurance",
        ),
        migrations.AddField(
            model_name="add_diver",
            name="certification_level",
            field=models.CharField(
                choices=[
                    ("Open Water", "Open Water"),
                    ("Advanced Open Water", "Advanced Open Water"),
                    ("Rescue Diver", "Rescue Diver"),
                    ("Divemaster", "Divemaster"),
                    ("Instructor", "Instructor"),
                ],
                default=0.00020596473883671115,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="add_diver",
            name="certification_agency",
            field=models.CharField(
                choices=[
                    ("PADI", "PADI"),
                    ("SSI", "SSI"),
                    ("NAUI", "NAUI"),
                    ("SDI", "SDI"),
                    ("CMAS", "CMAS"),
                    ("BSAC", "BSAC"),
                    ("ACUC", "ACUC"),
                    ("YMCA", "YMCA"),
                    ("NASDS", "NASDS"),
                    ("IANTD", "IANTD"),
                    ("PDIC", "PDIC"),
                    ("SEI", "SEI"),
                    ("TDI", "TDI"),
                    ("GUE", "GUE"),
                    ("RAID", "RAID"),
                    ("ANDI", "ANDI"),
                    ("FMAS", "FMAS"),
                    ("FFESSM", "FFESSM"),
                    ("SSAC", "SSAC"),
                    ("SAA", "SAA"),
                    ("CMAS", "CMAS"),
                ],
                max_length=100,
            ),
        ),
    ]
