# Generated by Django 4.2 on 2023-04-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("add_diver", "0002_alter_add_diver_student_insurance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="add_diver",
            name="dan_insurance",
            field=models.CharField(
                blank=True, help_text="Type in Dan Insurance Number", max_length=100
            ),
        ),
    ]
