# Generated by Django 4.2 on 2023-05-15 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("add_diver", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, help_text="Serial Number", max_length=100
                    ),
                ),
                (
                    "size",
                    models.CharField(blank=True, help_text="Size", max_length=100),
                ),
                (
                    "color",
                    models.CharField(blank=True, help_text="Color", max_length=100),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("New", "New"), ("Used", "Used")], max_length=100
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, help_text="Notes", max_length=100),
                ),
                ("available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_rental", models.DateField()),
                ("date_due", models.DateField()),
                (
                    "diver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="add_diver.diver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RentalEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rental_price", models.IntegerField()),
                ("deposit", models.IntegerField()),
                ("rental_insurance", models.IntegerField()),
                ("rental_insurance_price", models.IntegerField()),
                ("rental_total", models.IntegerField()),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment_rental.equipment",
                    ),
                ),
                (
                    "rental",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment_rental.rental",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rental",
            name="equipment_rental",
            field=models.ManyToManyField(
                through="equipment_rental.RentalEquipment",
                to="equipment_rental.equipment",
            ),
        ),
    ]
