# Generated by Django 4.2 on 2023-04-24 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("add_diver", "0003_alter_add_diver_dan_insurance"),
    ]

    operations = [
        migrations.CreateModel(
            name="equipment_rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_rental", models.DateField()),
                ("date_due", models.DateField()),
                (
                    "equipment_rented",
                    models.CharField(
                        choices=[
                            ("BCD", "BCD"),
                            ("Regulator", "Regulator"),
                            ("Wetsuit", "Wetsuit"),
                            ("Tank", "Tank"),
                            ("Weights", "Weights"),
                            ("Mask", "Mask"),
                            ("Fins", "Fins"),
                            ("Snorkel", "Snorkel"),
                            ("Dive Computer", "Dive Computer"),
                            ("Dive Light", "Dive Light"),
                            ("Dive Bag", "Dive Bag"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "equipment_serial_number",
                    models.CharField(
                        blank=True, help_text="Serial Number", max_length=100
                    ),
                ),
                (
                    "equipment_size",
                    models.CharField(blank=True, help_text="Size", max_length=100),
                ),
                (
                    "equipment_color",
                    models.CharField(blank=True, help_text="Color", max_length=100),
                ),
                (
                    "equipment_condition",
                    models.CharField(
                        choices=[("New", "New"), ("Used", "Used")], max_length=100
                    ),
                ),
                (
                    "equipment_notes",
                    models.CharField(blank=True, help_text="Notes", max_length=100),
                ),
                ("equipment_rental_price", models.IntegerField()),
                ("equipment_deposit", models.IntegerField()),
                ("equipment_rental_insurance", models.IntegerField()),
                ("equipment_rental_insurance_price", models.IntegerField()),
                ("equipment_rental_total", models.IntegerField()),
                ("equipment_rental_payment", models.IntegerField()),
                (
                    "equipment_rental_payment_type",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Check", "Check"),
                            ("Credit Card", "Credit Card"),
                            ("Debit Card", "Debit Card"),
                            ("Paypal", "Paypal"),
                            ("Venmo", "Venmo"),
                            ("Cash App", "Cash App"),
                            ("Zelle", "Zelle"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "equipment_rental_payment_notes",
                    models.CharField(blank=True, help_text="Notes", max_length=100),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="add_diver.add_diver",
                    ),
                ),
            ],
        ),
    ]
