# Generated by Django 4.2 on 2023-05-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment_rental", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(
                choices=[
                    ("regulator", "Regulator"),
                    ("regulator_console", "Regulator with Console"),
                    ("regulator_computer", "Regulator with Computer"),
                    ("sidemount_rig", "Sidemount Rig/Mount"),
                    ("bcd", "BCD"),
                    ("rebreather", "Rebreather"),
                    ("exposure_suit", "Exposure Suit"),
                    ("dry_suit", "Dry Suit"),
                    ("dive_skin", "Dive Skin"),
                    ("hood", "Hood"),
                    ("mask", "Mask"),
                    ("snorkel", "Snorkel"),
                    ("fins", "Fins"),
                    ("boots", "Boots"),
                    ("gloves", "Gloves"),
                    ("weights", "Weights"),
                    ("weight_belt", "Weight Belt"),
                    ("light", "Light"),
                    ("camera_video", "Camera/Video"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
