# Generated by Django 4.2 on 2023-05-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment_rental", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
