# Generated by Django 4.2.1 on 2023-05-25 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopify_integration", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShopifyUser",
        ),
    ]
