# Generated by Django 4.2 on 2023-04-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="airfill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("certification_number", models.IntegerField()),
                ("certification_agency", models.CharField(max_length=100)),
                ("Date_of_birth", models.DateField()),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.IntegerField()),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip", models.IntegerField()),
                ("tank_serial_number", models.CharField(max_length=100)),
                ("visual_date", models.IntegerField()),
                ("hydro_date", models.IntegerField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
    ]
