# Generated by Django 4.2 on 2023-04-29 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("add_diver", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="airfill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tank_serial_number", models.CharField(max_length=100)),
                ("visual_date", models.IntegerField()),
                ("hydro_date", models.IntegerField()),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="add_diver.add_diver",
                    ),
                ),
            ],
        ),
    ]
