# Generated by Django 4.2 on 2023-04-23 20:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airfill", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airfill",
            name="Date_of_birth",
        ),
        migrations.RemoveField(
            model_name="airfill",
            name="address",
        ),
        migrations.RemoveField(
            model_name="airfill",
            name="certification_agency",
        ),
        migrations.RemoveField(
            model_name="airfill",
            name="certification_number",
        ),
        migrations.RemoveField(
            model_name="airfill",
            name="city",
        ),
        migrations.RemoveField(
            model_name="airfill",
            name="date",
        ),
        migrations.RemoveField(
            model_name="airfill",
            name="email",
        ),
        migrations.RemoveField(
            model_name="airfill",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="airfill",
            name="state",
        ),
        migrations.RemoveField(
            model_name="airfill",
            name="time",
        ),
        migrations.RemoveField(
            model_name="airfill",
            name="zip",
        ),
    ]
